import Head from "next/head";
import axios from "axios";
import { GetStaticProps } from "next";

// Define os tipos de dados que você espera receber da API
interface Blog {
  texto: string;
  imagem: string;
}

interface EventData {
  evento: number;
  titulo: string;
  endereco: string;
  data: string;
  horario: string;
  cor_principal: string;
  cor_secundaria: string;
  link_lista: string;
  capa: string;
  blog: Blog[];
}

// Adicione o tipo de props
interface HomeProps {
  eventData: EventData | null;
}

export default function Home({ eventData }: HomeProps) {
  if (!eventData) {
    return <div>Carregando...</div>; // Ou alguma outra mensagem de erro
  }

  // Parse e formate a data
  const parsedDate = new Date(eventData.data);
  const formattedDate = new Intl.DateTimeFormat('pt-BR', {
    weekday: 'long',
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  }).format(parsedDate);

  return (
    <>
      <Head>
        <title>Convite Diego</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="banner-main" style={{ backgroundColor: eventData.cor_principal }}>
          <h1>{eventData.titulo}</h1>
          <div id="box-btn">            
            <h2>{formattedDate}</h2> {/* Data formatada */}
            <button type="button">Confirmar Presença</button>
          </div>
        </section>
        <section className="data-event">
          <div>
            <h2>Local</h2>
            <p>{eventData.endereco}</p>
          </div>
          <div>
            <h2>Horário</h2>
            <p>{eventData.horario}</p>
          </div>
          <div>
            <h2>Data</h2>
            <p>{formattedDate}</p> {/* Data formatada */}
          </div>
          <div>
            <h2>Fone</h2>
            <p>(Coloque o número do telefone aqui se houver)</p>
          </div>
          <div>
            <h2>Mapa</h2>
            <p><a href={eventData.capa} target="_blank" rel="noopener noreferrer">Ver mapa</a></p>
          </div>
        </section>
        <section className="news-events">
          <h2>Notícias</h2>
          <div className="news">
            {eventData.blog.map((newsItem, index) => (
              <div key={index}>
                <img src={newsItem.imagem} alt={newsItem.texto.substring(0, 30)} />
                <h3>{newsItem.texto.substring(0, 30)}...</h3>
                <p>{newsItem.texto}</p>
              </div>
            ))}
          </div>
        </section>
      </main>
    </>
  );
}

// Função para buscar os dados da API em tempo de build
export const getStaticProps: GetStaticProps = async () => {
  try {
    const response = await axios.get('https://evento.tecnodam.com.br/Evento/evento.rule?sys=EVT'); // URL do seu endpoint da API
    console.log(response.data); // Adicione esta linha
    const eventData: EventData = response.data;

    return {
      props: {
        eventData,
      },
    };
  } catch (error) {
    console.error(error);
    return {
      props: {
        eventData: null,
      },
    };
  }
}